### ISSUE TITLE
Failed to load images.

### ISSUE THREAD

**Issue by ghostwriter** [GrafiteInc/CMS#4]
Location: https://quarx.info/docs/

Missing Images:
-  https://quarx.info/images/1.jpg
-  https://quarx.info/images/2.jpg
-  https://quarx.info/images/3.jpg
-  https://quarx.info/images/4.jpg

**Comment by mlantz** [comment]
Thanks for the catch - all fixed now :)

**Comment by ghostwriter** [comment]
@mlantz you missed the `<a>` tags.
Clicking on the images results in `Failed to load image: https://quarx.info/images/{image_id}.jpg`

**Comment by mlantz** [comment]
blast! thanks :)
